name: Release CI
on:
  push:
    tags:
      - 'v*'

permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  process-version:
    uses: fastly/devex-reusable-workflows/.github/workflows/process-semver-v1.yml@kats/publish-javascript-package
  publish_npm:
    needs: process-version
    uses: fastly/devex-reusable-workflows/.github/workflows/publish-javascript-npmjs-v1.yml@kats/publish-javascript-package
    with:
      version: ${{ needs.process-version.outputs.version }}
      dist_tag: ${{ needs.process-version.outputs.dist_tag }}
  publish_github:
    needs: process-version
    uses: fastly/devex-reusable-workflows/.github/workflows/publish-javascript-github-v1.yml@kats/publish-javascript-package
    with:
      version: ${{ needs.process-version.outputs.version }}
      dist_tag: ${{ needs.process-version.outputs.dist_tag }}
